# Generated by Django 4.1.5 on 2023-05-23 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('ID_Categoria', models.AutoField(primary_key=True, serialize=False, verbose_name='Código de la Categoria')),
                ('Categoria', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('ID_Compra', models.AutoField(primary_key=True, serialize=False, verbose_name='Código de Compra')),
                ('F_Entrega', models.DateField()),
                ('F_Despacho', models.DateField()),
                ('Estado', models.CharField(max_length=30)),
                ('Total', models.CharField(max_length=30)),
                ('Costo_Envio', models.CharField(max_length=30)),
                ('Carro', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('ID_Comuna', models.AutoField(primary_key=True, serialize=False, verbose_name='Código de la Comuna')),
                ('Comuna', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Preguntas',
            fields=[
                ('ID_Preguntas', models.AutoField(primary_key=True, serialize=False, verbose_name='Código de Pregunta')),
                ('Pregunta', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('ID_Region', models.AutoField(primary_key=True, serialize=False, verbose_name='Código de la Region')),
                ('Region', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('ID_Rol', models.AutoField(primary_key=True, serialize=False, verbose_name='Código del ROL')),
                ('Rol', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('ID_Tipo', models.AutoField(primary_key=True, serialize=False, verbose_name='Código del Tipo')),
                ('Tipo', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('ID_Usuario', models.AutoField(primary_key=True, serialize=False, verbose_name='Código del Usuario')),
                ('Rut', models.IntegerField()),
                ('Nombre', models.CharField(max_length=30)),
                ('Apellido', models.CharField(max_length=30)),
                ('Correo', models.CharField(max_length=30)),
                ('Num_Celular', models.IntegerField()),
                ('Clave', models.CharField(max_length=30)),
                ('preguntas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.preguntas')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.rol')),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('ID_Producto', models.AutoField(primary_key=True, serialize=False, verbose_name='Código del Producto')),
                ('Nombre', models.CharField(max_length=30)),
                ('Descripcion', models.CharField(max_length=30)),
                ('Precio', models.CharField(max_length=30)),
                ('Stock', models.CharField(max_length=30)),
                ('Foto', models.ImageField(upload_to='Producto')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.categoria')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.tipo')),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('ID_Direccion', models.AutoField(primary_key=True, serialize=False, verbose_name='Código de la Dirección')),
                ('Calle', models.CharField(max_length=30)),
                ('Num_Casa', models.IntegerField()),
                ('comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.comuna')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Detalles',
            fields=[
                ('ID_Detalle', models.AutoField(primary_key=True, serialize=False, verbose_name='Código Detalle')),
                ('Cantidad', models.CharField(max_length=30)),
                ('Subtotal', models.CharField(max_length=30)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.compra')),
            ],
        ),
        migrations.AddField(
            model_name='comuna',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.region'),
        ),
        migrations.AddField(
            model_name='compra',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.usuario'),
        ),
    ]
