# Generated by Django 4.1.5 on 2023-06-08 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='Respuesta',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
