# Generated by Django 4.2.1 on 2023-06-08 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_usuario_respuesta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='Num_Celular',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='Rut',
            field=models.CharField(max_length=10),
        ),
    ]
