# Generated by Django 4.2.2 on 2023-06-14 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_usuario_num_celular_alter_usuario_rut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='Correo',
            field=models.CharField(max_length=100),
        ),
    ]
